# This is a basic workflow to help you get started with Actions

name: Freds First Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  freds_first_job:
    runs-on: ubuntu-latest #linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: |
          echo "This is Fred's first workflow."
          echo "This is a test of GitHub Actions."
