# This is a basic workflow to help you get started with Actions

name: Freds First Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  freds_first_job:
    runs-on: ubuntu-latest #linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Install / Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan

